# bonus program made by me (@BOBeirne) to read data from the census2010.py file generated by readCensusExcel.py from censuspopdata.xlsx

import census2010
state = input('Enter the state abbreviation: ')
county = input('Enter the county name: ')

census2010.allData[state][county]
county_pop = census2010.allData[state][county]['pop']

print(f'The 2010 population of {county}, {state} was {county_pop}.')